name: Build on push

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 18
      uses: actions/setup-java@v1
      with:
        java-version: 1.18
    - name: Make gradlew executable
      run: chmod +x gradlew
    - name: Build with Gradle
      uses: burrunan/gradle-cache-action@v1
      with:
        job-id: jdk16
        gradle-version: wrapper
        arguments: build
